EvolutyzCorner.UI.Web/Controllers/OrganizationAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Evolutyz.Entities;
using Evolutyz.Business;

using System.IO;
using System.Web.Configuration;

namespace EvolutyzCorner.UI.Web.Controllers
{

    [Authorize]
    [EvolutyzCorner.UI.Web.MvcApplication.SessionExpire]
    [EvolutyzCorner.UI.Web.MvcApplication.NoDirectAccess]
    public class OrganizationAccountController : Controller
    {
        public ActionResult Index()
        {

            List<LookupStatusDetail> objStatusList = new List<LookupStatusDetail>();
            objStatusList.Add(new LookupStatusDetail { StatusID = 1, Status = "Active" });
            objStatusList.Add(new LookupStatusDetail { StatusID = 0, Status = "InActive" });

            var objStList = from cl in objStatusList
                            orderby cl.StatusID
                            select new
                            {
                                value = cl.StatusID,
                                text = cl.Status  
                            };
            ViewBag.Status = objStList;

            HomeController hm = new HomeController();
            var obj = hm.GetAdminMenu();
            foreach (var item in obj)
            {

                if (item.ModuleName == "Add Account")
                {
                    var mk = item.ModuleAccessType;


                    ViewBag.a = mk;

                }

            }


            return View();
        }

       


        public ActionResult showAllRecords()
        {
            List<OrganizationAccountEntity> AccDetails = null;
            OrganizationAccountEntity currentAccount = new OrganizationAccountEntity();
            try
            {
                if (ViewBag.currentRecord != null)
                {
                    currentAccount = ViewBag.currentRecord;
                    ViewBag.currentRecord = null;
                }
                else
                {

                    var objDtl = new OrganizationAccountComponent();
                    AccDetails = objDtl.GetOrganizationAccounts();
                    currentAccount = AccDetails.FirstOrDefault();
                }
            }
            catch (Exception ex)
            {
                return null;
            }

            return View(currentAccount);
        }

        public ActionResult BrowseAccountRecords(int id, string navigation)
        {
            OrganizationAccountEntity currentRecord = null;
            try
            {
                var objDtl = new OrganizationAccountComponent();
                currentRecord = objDtl.BrowseAccountRecords(id, navigation);
                ViewBag.currentRecord = currentRecord;
            }
            catch (Exception ex)
            {
                return null;
            }

            return View("showAllRecords");
        }
        public string CreateOrganizationAccount(OrganizationAccountEntity AccDtl)
        {
            string strResponse = string.Empty;
            var orgcomponent = new OrganizationAccountComponent();
            UserSessionInfo objSessioninfo = Session["UserSessionInfo"] as UserSessionInfo;
            int _userID = objSessioninfo.UserId;
            AccDtl.Acc_CreatedBy = _userID;
            string imagename = string.Empty;
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                var fileName = "/uploadimages/Images/" + file.FileName;
                imagename = file.FileName;
                var imagepath = Server.MapPath(fileName);
                file.SaveAs(imagepath);
            }
            if (imagename == "")
            {
                AccDtl.Acc_CompanyLogo = "User.png";
            }
            else
            {
                AccDtl.Acc_CompanyLogo = imagename;
            }
            
            int r = orgcomponent.AddOrganizationAccount(AccDtl);
            if (r ==1)
            {
                strResponse = "Record created successfully";
            }
            else if (r == 0)
            {
                strResponse = "Record already exists";
            }
            else if (r ==-1)
            {
                strResponse = "Please Fill Mandatory Fields";
            }
            else if (r ==2)
            {
                strResponse = "AccountName already exists";
            }
            else if (r ==3)
            {
                strResponse = "AccountCode already exists";
            }
            //else if (r == 4)
            //{
            //    strResponse = "AccountCode already exists";
            //}
            return strResponse;

        }

        public string UpdateOrganizationAccount(OrganizationAccountEntity accdtl)
        {
            var orgcomponent = new OrganizationAccountComponent();
            UserSessionInfo objSessioninfo = Session["UserSessionInfo"] as UserSessionInfo;
            int _userID = objSessioninfo.UserId;

            accdtl.Acc_ModifiedBy = _userID;
            string imagename = string.Empty;
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                var fileName = "/uploadimages/Images/" + file.FileName;
                imagename = file.FileName;
                var imagepath = Server.MapPath(fileName);
                file.SaveAs(imagepath);
            }
            else
            {
                imagename = accdtl.Acc_CompanyLogo;
            }
            accdtl.Acc_CompanyLogo = imagename;  
            string response = orgcomponent.UpdateOrganizationAccount(accdtl);
            return response;

        }


        //public string AddOrganizationAccount(OrganizationAccountEntity AccDtl)
        //{
        //    string strResponse = string.Empty;
        //        short AccCurrentVersion = 0;
        //    try
        //    {
        //            var orgComponent = new OrganizationAccountComponent();
        //            var currentAccountDetails = orgComponent.GetOrganizationAccountByID(AccDtl.Acc_AccountID);
        //            int AccID = currentAccountDetails.Acc_AccountID;
        //            AccCurrentVersion = currentAccountDetails.Acc_Version;
        //            bool AccCurrentStatus = false;
        //            //AccDtl.Acc_Version  = ++currentAccountDetails.Acc_Version;

        //            //check for version and active status
        //            if ((ValueProviderResult)ModelState["Acc_ActiveStatus"].Value != null)
        //            {
        //                ModelState.SetModelValue("Acc_ActiveStatus", (ValueProviderResult)ModelState["Acc_ActiveStatus"].Value);
        //                ModelState["Acc_ActiveStatus"].Errors.Clear();
        //                AccCurrentStatus = Request.Form["Acc_ActiveStatus"] == "1" ? true : false;
        //                //AccCurrentStatus =((ValueProviderResult)ModelState["Acc_ActiveStatus"].Value.AttemptedValue);
        //            }
        //            dynamic versionValue = (ValueProviderResult)ModelState["Acc_Version"].Value;
        //            if (versionValue != null)
        //            {
        //                ModelState.SetModelValue("Acc_Version", (ValueProviderResult)ModelState["Acc_Version"].Value);
        //                ModelState["Acc_Version"].Errors.Clear();
        //            }
        //        if (ModelState.IsValid)
        //        {
        //            try
        //            {
        //                // Upload Company Logo
        //                string fileExtension = string.Empty;
        //                string newFilename = string.Empty;
        //                if (Request.Files.Count > 0)
        //                {
        //                    var mediaFile = Request.Files[0];

        //                    if (mediaFile != null)
        //                    {
        //                        var fileName = Path.GetFileName(mediaFile.FileName);
        //                        var path = Path.Combine(Server.MapPath("~" + @"\Content\images\CompanyLogos\"), fileName);
        //                        mediaFile.SaveAs(path);
        //                        fileExtension = Path.GetExtension(path).ToLower();

        //                        //renaming files 
        //                        string newName = AccDtl.Acc_AccountID.ToString();
        //                        ViewBag.ImagePath ="~" + @"\Content\images\CompanyLogos\"+ newName + fileExtension;
        //                        if (System.IO.File.Exists(path))
        //                        {
        //                            AccDtl.Acc_CompanyLogo = newName + "." + fileExtension; ;
        //                            System.IO.File.Copy(path, Path.Combine(Server.MapPath("~" + @"\Content\images\CompanyLogos\"), newName + fileExtension), true);
        //                            System.IO.File.Delete(fileName);
        //                        }
        //                    }
        //                }
        //            }
        //            catch (Exception ex)
        //            {
        //                return strResponse;
        //            }

        //                UserSessionInfo objSessioninfo = Session["UserSessionInfo"] as UserSessionInfo;
        //            int _userID = objSessioninfo.UserId;
        //            AccDtl.Acc_ModifiedBy = _userID;
        //                //while udating increment version by1
        //                AccDtl.Acc_Version = ++AccCurrentVersion;
        //                AccDtl.Acc_ActiveStatus = AccCurrentStatus;
        //            var Org = new OrganizationAccountComponent();
        //            int r = Org.UpdateOrganizationAccount(AccDtl);
        //            if (r > 0)
        //            {
        //                strResponse = "Record updated successfully";
        //            }
        //            else if (r == 0)
        //            {

EvolutyzCorner.UI.Web/Views/OrganizationAccount/_LoadAccount.cshtml
@model Evolutyz.Entities.OrganizationAccountEntity

@using (Html.BeginForm("CreateOrganizationAccount", "OrganizationAccount", FormMethod.Post, new { ReturnUrl = ViewBag.ReturnUrl, id = "AccountForm" }))
{
    @*@Html.AntiForgeryToken()
    @Html.ValidationSummary(true)*@

    <div class="form-horizontal">
        <div class="col-sm-12">
            <div class="form-group">

                <div class="col-md-12">
                    <label class="col-md-4"> Account Code</label>
                    <div class="col-md-8">
                        @Html.HiddenFor(m => m.Acc_AccountID, new { id = "hdnAccountID" })
                        @Html.HiddenFor(m => m.Acc_Version, new { id = "hdnVersion" })
                        @Html.TextBoxFor(m => m.Acc_AccountCode, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(m => m.Acc_AccountCode)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-sm-4"> Account Name :</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Acc_AccountName, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(m => m.Acc_AccountName)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-sm-4"> Account Description :</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Acc_AccountDescription, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(m => m.Acc_AccountDescription)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-sm-4"> Account Logo :</label>
                    <div class="col-sm-8">
                        <input type="file" id="fileUpload" name="fileUpload" />
                        @Html.TextBoxFor(m => m.Acc_CompanyLogo, new { @class = "form-control", style = "display: none;" })
                        @*@Html.ValidationMessageFor(m => m.Acc_CompanyLogo  )*@
                        <img id="imgLogo" src='#' class="img-responsive" alt="Logo" width="150" height="55"/>                        
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-md-4"> Email :</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(m => m.Acc_EmailID, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Acc_EmailID)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-sm-4"> Mobile :</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Acc_MobileNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Acc_MobileNumber)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-sm-4"> Phone :</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.Acc_PhoneNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Acc_PhoneNumber)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label class="col-sm-4">Status :</label>
                    <div class="col-sm-8">
                        @*@Html.DropDownListFor(x => x.Acc_ActiveStatus, new List<SelectListItem> { new SelectListItem { Text = "Active", Value = "True" }, new SelectListItem { Text = "InActive", Value = "False" } }, "Select Status", new { @class = "form-control" })*@
                        @Html.DropDownListFor(x => x.Acc_ActiveStatus, new SelectList(@ViewBag.Status, "value", "text"), "Select Status", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Acc_ActiveStatus)
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <div class="col-sm-12">
                    <div class="col-sm-12">
                        <input type="button" id="btnClose" value="Close"  class="btn btn-default pull-right" />&nbsp;&nbsp;&nbsp;
                        <input type="button" id="btnAddAccount" value="Create" class="btn btn-success pull-right" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#btnClose').click(function () {
            $('#ContainerGridAccountDetail').hide();
        });
                
    $('#btnAddAccount').click(function () {
        var switch_val = $(this).val();
        var _accountID = $('#hdnAccountID').val();
        alert('_accountID : ' + _accountID + ', Button Text : ' + switch_val);

        var file = document.getElementById("fileUpload").files[0];
        var formData = new FormData();
        formData.append("Acc_AccountID", _accountID);
        formData.append("Acc_AccountCode", $('#Acc_AccountCode').val());
        //formData.append("Acc_AccountCode", $('#hdnAccountID').val());
        formData.append("Acc_AccountName", $('#Acc_AccountName').val());
        formData.append("Acc_AccountDescription", $('#Acc_AccountDescription').val());
        formData.append("Acc_EmailID", $('#Acc_EmailID').val());
        formData.append("Acc_MobileNumber", $('#Acc_MobileNumber').val());
        formData.append("Acc_PhoneNumber", $('#Acc_PhoneNumber').val());

        alert('Active Status : ' + $('#Acc_ActiveStatus').val());

        formData.append("Acc_ActiveStatus", $('#Acc_ActiveStatus').val());
        formData.append("Acc_AccountCode", $('#hdnAccountID').val());
        formData.append("Acc_Version", $('#hdnVersion').val());
        formData.append("Acc_CompanyLogo", file);

        if (switch_val.toUpperCase() === "ADD") {

            formData.append("Acc_Version", 1);

            $.ajax({
                    url: '@Url.Action("CreateOrganizationAccount", "OrganizationAccount")',
                    cache: false,
                    type: 'POST',
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (data) {
                        $('#jQGridDetail').jqGrid('setGridParam', { datatype: 'json' }).trigger('reloadGrid');
                        $(".custom-grid-form").hide();
                        alert('Successfully Added');
                    }
                });
        }
        else if (switch_val.toUpperCase() === "UPDATE") {                
            $.ajax({
                url: '@Url.Action("UpdateOrganizationAccount", "OrganizationAccount")',
                async: false,
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    $('#jQGridDetail').jqGrid('setGridParam', { datatype: 'json' }).trigger('reloadGrid');
                    $(".custom-grid-form").hide();
                    alert('Successfully Updated');
                }
            });
        }
    });
});

</script>

EvolutyzCorner.UI.Web/Views/OrganizationAccount/_LoadVersionHistory.cshtml
@model Evolutyz.Entities.OrganizationAccountEntity
@{
    ViewBag.Title = "Organization Account History List";
   
    var OrgAccDetails = ViewBag.OrgAccDetails;
}
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    @{
        if (OrgAccDetails != null)
        {
            foreach (var orgaccdet in OrgAccDetails)
            {
                var i = 0;
                <a>
                    <input type="checkbox">
                    orgaccdet[i].Acc_Version
                </a>
                i++;
            }
        }
    }

    <a>
        <input type="checkbox">
        E.0.0.1 15/2/2017
    </a> <a>
        <input type="checkbox">
        E.0.0.2 20/4/2017
    </a> <a>
        <input type="checkbox">
        E.0.0.3 30/6/2017
    </a> <a>
        <input type="checkbox">
        E.0.0.4 10/8/2017
    </a> <a>
        <input type="checkbox">
        E.0.0.4 20/10/2017
    </a> <a data-toggle="modal" data-target="#compare">
        <button type="button" class="btn btn-block btn-warning">Compare</button>
    </a>
</div>

EvolutyzCorner.UI.Web/Views/OrganizationAccount/showAllRecords.cshtml
@model Evolutyz.Entities.OrganizationAccountEntity

<div>
    <h4>Organization Account</h4>
    <hr />
    <fieldset>
        <legend>Author</legend>
        <div class="=row">
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Acc_AccountCode)
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Acc_AccountCode)
            </div>
        </div>

        <div class="display-label">
            @Html.HiddenFor(model => model.Acc_AccountID, new { id = "hdnAccountID" })
            @Html.DisplayNameFor(model => model.Acc_AccountName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_AccountName)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Acc_AccountDescription)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_AccountDescription)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Acc_EmailID)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_EmailID)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Acc_MobileNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_MobileNumber)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Acc_PhoneNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_PhoneNumber)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Acc_CompanyLogo)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_CompanyLogo)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Acc_Version)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Acc_Version)
        </div>
        <p>
            <input type="submit" value="Previous" />
            <input type="submit" value="Next" />
            @*<input type="button" value="First" id="btnFirst" />&nbsp;<input type="button" value="Previous" id="btnPrevious" />&nbsp;
            <input type="button" value="Next" id="btnNext" />&nbsp;<input type="button" value="Last" id="btnLast" />*@
        </p>
    </fieldset>



    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Acc_AccountID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_AccountID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_AccountCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_AccountCode)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_AccountName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_AccountName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_AccountDescription)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_AccountDescription)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_EmailID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_EmailID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_MobileNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_MobileNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_PhoneNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_PhoneNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_CompanyLogo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_CompanyLogo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_ActiveStatus)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_ActiveStatus)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_Version)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_Version)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_CreatedBy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_CreatedBy)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_ModifiedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_ModifiedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_ModifiedBy)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_ModifiedBy)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Acc_isDeleted)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Acc_isDeleted)
            </dd>

        </dl>*@
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<script>
    function fetchRecord(_id, nav) {
        alert('id:' + _id + ', Navigation: ' + nav);

        $.ajax({
            url: "@Url.Action("browseAccountRecords", "OrganizationAccount")",
            data: { id: _id, navigation: nav },
            //type: "GET",
            //dataType: "json",
            success: function (data) {
                $('#hdnAccountID').val(data.Acc_AccountID);
                $('#Acc_AccountCode').val(data.Acc_AccountCode);
                $('#Acc_AccountName').val(data.Acc_AccountName);
                $('#Acc_AccountDescription').val(data.Acc_AccountDescription);
                $('#Acc_EmailID').val(data.Acc_EmailID);
                $('#Acc_MobileNumber').val(data.Acc_MobileNumber);
                $("#Acc_PhoneNumber").val(data.Acc_PhoneNumber)
                ////$('#Acc_ActiveStatus').val(data.Acc_ActiveStatus);
                //if (data.Acc_ActiveStatus) {
                //    $('#Acc_ActiveStatus').val("1");
                //}
                //else {
                //    $('#Acc_ActiveStatus').val("0");
                //}

                //var _imgLogo = data.Acc_CompanyLogo;
                //var _imgPath = "/Content/images/CompanyLogos/";
                ////$('#Acc_CompanyLogo').val(imgLogo);

                //if (_imgLogo != null && _imgLogo != "")
                //{
                //    $('#imgLogo').show();
                //    $('#imgLogo').prop('src', _imgPath + _imgLogo);
                //}
            },
            error: function () {
                alert("Failed! Please try again.");
            }
        });
    }

    $("#btnFirst").click(function () {
        fetchRecord(0,"First")
    });
    $("#btnLast").click(function () {
        var id = $('#hdnAccountID').val();
        fetchRecord(id, "Last")
    });
    $("#btnNext").click(function () {
        var id = $('#hdnAccountID').val();
        fetchRecord(id, "Next")
    });
    $("#btnPrevious").click(function () {
        var id = $('#hdnAccountID').val();
        fetchRecord(id, "Previous")
    });
</script>